import {createClient,getAccessToken} from '@base44/sdk';
import {encodeBytes,decodeBytes} from '../native/encoding.ts';
const appId=import.meta.env.VITE_BASE44_APP_ID;
export const configured=typeof appId==='string'&&appId.length>0;
export const base44=createClient({appId:appId||'not-linked',appBaseUrl:window.location.origin,analytics:{enabled:false}});
const originalFetch=window.fetch.bind(window);
let connection:any=null;
const pending=new Map<string,{parts:string[];next:number;resolve:(r:Response)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
function connect(){if(connection)return connection;connection=base44.actors.StaffingHub('always-nursing-records-v1').connect();connection.subscribe((msg:any)=>{const task=pending.get(msg.id);if(!task)return;if(msg.type==='error'){clearTimeout(task.timer);pending.delete(msg.id);task.reject(new Error(msg.message));return;}if(msg.type!=='reply-part'||msg.index!==task.next)return;task.parts.push(msg.data);task.next++;if(task.next!==msg.total)return;clearTimeout(task.timer);pending.delete(msg.id);try{const r=JSON.parse(task.parts.join(''));task.resolve(new Response(decodeBytes(r.body) as BodyInit,{status:r.status,headers:r.headers}));}catch{task.reject(new Error('Could Not Read Backend Response'));}});return connection;}
export function disconnect(){connection?.close();connection=null;for(const task of pending.values()){clearTimeout(task.timer);task.reject(new Error('Signed Out'));}pending.clear();}
export async function nursingFetch(input:RequestInfo|URL,init?:RequestInit):Promise<Response>{const request=new Request(input instanceof Request?input:new URL(String(input),window.location.origin),init);const url=new URL(request.url);if(url.origin!==window.location.origin||!url.pathname.startsWith('/api/'))return originalFetch(input,init);if(!configured)throw new Error('Link This Project To Your Base44 App First');if(request.signal.aborted)throw new DOMException('Aborted','AbortError');const body=request.method==='POST'?encodeBytes(new Uint8Array(await request.arrayBuffer())):undefined;const id=crypto.randomUUID(),payload=JSON.stringify({id,path:url.pathname+url.search,method:request.method,authToken:getAccessToken(),contentType:request.headers.get('Content-Type')||undefined,range:request.headers.get('Range')||undefined,body});if(payload.length>16800000)throw new Error('File Exceeds Transport Limit');return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Request Timed Out. Refresh To Check Whether It Was Saved Before Retrying.'));},180000);const finish=(r:Response)=>{request.signal.removeEventListener('abort',abort);resolve(r);};const fail=(e:Error)=>{request.signal.removeEventListener('abort',abort);reject(e);};const abort=()=>{const p=pending.get(id);if(p){clearTimeout(p.timer);pending.delete(id);fail(new DOMException('Aborted','AbortError'));}};pending.set(id,{parts:[],next:0,resolve:finish,reject:fail,timer});request.signal.addEventListener('abort',abort,{once:true});try{const conn=connect(),size=48000,total=Math.ceil(payload.length/size);for(let index=0;index<total;index++)conn.send({type:'part',id,index,total,data:payload.slice(index*size,(index+1)*size)});}catch(e){clearTimeout(timer);pending.delete(id);fail(e instanceof Error?e:new Error('Connection Failed'));}});}
export function installTransport(){window.fetch=nursingFetch;document.addEventListener('click',event=>{const element=(event.target as Element)?.closest?.('a[href]') as HTMLAnchorElement|null;if(!element)return;const url=new URL(element.href,window.location.href);if(url.origin!==window.location.origin||!url.pathname.startsWith('/api/'))return;event.preventDefault();const preview=url.searchParams.get('view')==='1'||element.target==='_blank';const tab=preview?window.open('about:blank','_blank'):null;void nursingFetch(url).then(async response=>{if(response.status>=300&&response.status<400&&response.headers.get('location')){const destination=new URL(response.headers.get('location')!,window.location.origin);if(destination.protocol!=='https:'&&destination.origin!==window.location.origin)throw new Error('Invalid Destination');if(tab){tab.opener=null;tab.location.href=destination.href;}else window.location.assign(destination.href);return;}if(!response.ok)throw new Error('Document Unavailable Or Access Denied');const blob=URL.createObjectURL(await response.blob());if(tab){tab.opener=null;tab.location.href=blob;setTimeout(()=>URL.revokeObjectURL(blob),300000);}else{const link=document.createElement('a');link.href=blob;const header=response.headers.get('Content-Disposition')||'';const name=header.match(/filename\*=UTF-8''([^;]+)/)?.[1];link.download=element.download||(name?decodeURIComponent(name):'Always-Nursing-Document');document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(blob),60000);}}).catch(error=>{tab?.close();window.alert(error.message);});});}
